version: '3.8'

services:
  # O Banco de Dados (nosso "cofre" de dados ópticos)
  db:
    image: postgres:15-alpine
    container_name: optical_db
    restart: always
    environment:
      POSTGRES_USER: sentinel_user
      POSTGRES_PASSWORD: sentinel_password
      POSTGRES_DB: optical_health
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # A Ferramenta de Visualização
  metabase:
    image: metabase/metabase:latest
    container_name: optical_viz
    restart: always
    ports:
      - "3000:3000"
    # Removemos as variáveis de DB interno para evitar o erro de 'database does not exist'
    depends_on:
      - db

volumes:
  postgres_data: